# Creating Numpy array

In [1]:
import numpy as np

In [2]:
np.array([2,4,56,422,32,1]) # 1D array 

array([  2,   4,  56, 422,  32,   1])

In [3]:
a = np.array([2,4,56,422,32,1]) #Vector 
print(a) 

[  2   4  56 422  32   1]


In [4]:
type(a) 


numpy.ndarray

In [5]:
# 2D Array ( Matrix) 
 
new = np.array([[45,34,22,2],[24,55,3,22]]) 
print(new) 

[[45 34 22  2]
 [24 55  3 22]]


In [9]:
# 3 D ---- # Tensor 
np.array( [[2,3,33,4,45],[23,45,56,66,2],[357,523,32,24,2],[32,32,44,33,234]] )

array([[  2,   3,  33,   4,  45],
       [ 23,  45,  56,  66,   2],
       [357, 523,  32,  24,   2],
       [ 32,  32,  44,  33, 234]])

# dtype 
The desired data-type for the array. If not given, then the type willbe determined as the 
minimum type required to hold the objects in thesequence. 

In [10]:
np.array([11,23,44] , dtype =float) 

array([11., 23., 44.])

In [11]:
np.array([11,23,44] , dtype =bool) 

array([ True,  True,  True])

In [12]:
np.array([11,23,44] , dtype =complex) 

array([11.+0.j, 23.+0.j, 44.+0.j])

# Arange 
 
arange can be called with a varying number of positional arguments 

In [14]:
np.arange(1,25)  # 1-included , 25 - last one got excluded

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [15]:
np.arange(1,25,2) #strides ---> Alternate numbers 

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

# Reshape 
 
Both of number products should be equal to umber of Items present inside the array.

In [16]:
np.arange(1,11).reshape(5,2) # converted 5 rows and 2 columns

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [17]:
np.arange(1,11).reshape(2,5) # converted 2 rows and 5 columns 

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [18]:
np.arange(1,13).reshape(3,4) # converted 3 rows and 4 columns

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# Ones & Zeros 
 
you can initialize the values and create values . ex: in deep learning weight shape 

In [20]:
# np.ones and np.zeros 
 
np.ones((3,4)) # we have to mention iside tuple

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
# Another Type ---> random() 
np.random.random((4,3)) 

array([[0.93597689, 0.18863332, 0.94679285],
       [0.71796124, 0.62466352, 0.19041343],
       [0.66998153, 0.52602734, 0.30146198],
       [0.11849954, 0.16942293, 0.14373237]])

# Linspace 
 
It is also called as Linearly space , Linearly separable,in a given range at equal distance it 
creates points. 

In [25]:
np.linspace(-10,10,10) # here: lower range,upper range ,number of items to 

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [26]:
np.linspace(-2,12,6) 

array([-2. ,  0.8,  3.6,  6.4,  9.2, 12. ])

# Identity 
 
indentity matrix is that diagonal items will be ones and evrything will be zeros

In [27]:
# creating the indentity matrix 
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

# Array Attributes 

In [29]:
a1 = np.arange(10) # 1D 
a1 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
a2 =np.arange(12, dtype =float).reshape(3,4) # Matrix 
a2 

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [31]:
a3 = np.arange(8).reshape(2,2,2) # 3D --> Tensor 
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

# N-dim 
To findout given arrays number of dimensions 

In [32]:
a1.ndim

1

In [33]:
a2.ndim

2

In [34]:
a3.ndim 


3

# Shape 
gives each item consist of no.of rows and np.of column 

In [35]:
a1.shape # 1D array has 10 Items 

(10,)

In [36]:
a2.shape # 3 rows and 4 columns 

(3, 4)

In [37]:
a3.shape # first ,2 says it consists of 2D arrays .2,2 gives no.of rows 

(2, 2, 2)

# Size 
gives number of items 

In [38]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [39]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [40]:
a2.size

12

# Item size 
Memory occupied by the item 

In [41]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
a1.itemsize

8

In [43]:
a2.itemsize

8

In [45]:
a3.itemsize

8

# dtype 
gives data type of the item

In [46]:
print(a1.dtype) 
print(a2.dtype) 
print(a3.dtype) 

int64
float64
int64


# Changing Data Type

In [47]:
#astype 
 
x = np.array([33, 22, 2.5]) 
x

array([33. , 22. ,  2.5])

In [48]:
x.astype(int) 

array([33, 22,  2])

# Array operations 

In [51]:
z1 = np.arange(12).reshape(3,4) 
z2 = np.arange(12,24).reshape(3,4) 
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [52]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# Scalar operations 
Scalar operations on Numpy arrays include performing addition or subtraction, or multiplication 
on each element of a Numpy array. 

In [53]:
# arithmetic 
z1 + 2 

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [54]:
# Subtraction 
z1 - 2 

array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [55]:
# Multiplication 
z1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [56]:
# power 
z1 ** 2 

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [57]:
## Modulo 
z1 % 2 


array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]])

# Relational Operators 
The relational operators are also known as comparison operators, their main function is to 
return either a true or false based on the value of operands.

In [58]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [59]:
z2 > 2

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [60]:
z2 >20

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True]])

# Vector Operation 
We can apply on both numpy array 

In [61]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [62]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [63]:
z1 + z2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [64]:
z1 * z2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [65]:
z1 - z2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [66]:
z1 / z2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

# Array Functions 

In [67]:
k1 = np.random.random((3,3)) 
k1 = np.round(k1*100) 
k1 

array([[44., 40., 39.],
       [68., 80., 23.],
       [59., 39., 58.]])

In [68]:
# Max 
np.max(k1)

np.float64(80.0)

In [69]:
# min 
np.min(k1)

np.float64(23.0)

In [70]:
# sum 
np.sum(k1)

np.float64(450.0)

In [71]:
# prod ----> Multiplication 
 
np.prod(k1)

np.float64(1146168906854400.0)

# In Numpy
0 = column , 1 = row

In [72]:
# if we want maximum of every row 
 
np.max(k1, axis = 1) 

array([44., 80., 59.])

In [73]:
# maximum of every column 
 
np.max(k1, axis = 0) 

array([68., 80., 58.])

In [74]:
# product of every column 
 
np.prod(k1, axis = 0) 

array([176528., 124800.,  52026.])

## Statistics related fuctions 

In [75]:
k1

array([[44., 40., 39.],
       [68., 80., 23.],
       [59., 39., 58.]])

In [76]:
np.mean(k1)

np.float64(50.0)

In [77]:
k1.mean(axis=0) 

array([57., 53., 40.])

In [78]:
np.median(k1)

np.float64(44.0)

In [79]:
np.median(k1, axis = 1)

array([40., 68., 58.])

In [80]:
np.std(k1) 

np.float64(16.586473739499638)

In [81]:
np.std(k1, axis =0)

array([ 9.89949494, 19.09624745, 14.30617582])

In [82]:
np.var(k1) 

np.float64(275.1111111111111)

### Trignometry Functions 

In [83]:
np.sin(k1) # sin

array([[ 0.01770193,  0.74511316,  0.96379539],
       [-0.89792768, -0.99388865, -0.8462204 ],
       [ 0.63673801,  0.96379539,  0.99287265]])

In [84]:
np.cos(k1) 

array([[ 0.99984331, -0.66693806,  0.26664293],
       [ 0.44014302, -0.11038724, -0.53283302],
       [-0.77108022,  0.26664293,  0.11918014]])

In [85]:
np.tan(k1) 

array([[ 0.0177047 , -1.11721493,  3.61455441],
       [-2.0400816 ,  9.00365495,  1.58815308],
       [-0.82577401,  3.61455441,  8.33085685]])

# dot product 
The numpy module of Python provides a function to perform the dot product of two arrays.

In [86]:
s2 = np.arange(12).reshape(3,4) 
s3 = np.arange(12,24).reshape(4,3)
s2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [87]:
s3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [88]:
np.dot(s2,s3) # dot product of s2 , s3

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

# Log and Exponents 

In [89]:
np.exp(s2)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

# Round / Floor / Ceil

#### 1. round 
The numpy.round() function rounds the elements of an array to the nearest integer or to the 
specified number of decimals. 

In [90]:
# Round to the nearest integer 
arr = np.array([1.2, 2.7, 3.5, 4.9]) 
rounded_arr = np.round(arr) 
print(rounded_arr) 

[1. 3. 4. 5.]


In [91]:
# Round to two decimals 
arr = np.array([1.234, 2.567, 3.891]) 
rounded_arr = np.round(arr, decimals=2) 
print(rounded_arr)

[1.23 2.57 3.89]


In [92]:
#randomly 
np.round(np.random.random((2,3))*100) 


array([[30., 42., 21.],
       [70., 88., 24.]])

#### 2. floor 
The numpy.floor() function returns the largest integer less than or equal to each element of an 
array. 


In [93]:
# Floor operation 
arr = np.array([1.2, 2.7, 3.5, 4.9]) 
floored_arr = np.floor(arr) 
print(floored_arr)

[1. 2. 3. 4.]


In [94]:
np.floor(np.random.random((2,3))*100) # gives the smallest integer 

array([[83., 15., 50.],
       [23., 85., 80.]])

#### 3. Ceil 
The numpy.ceil() function returns the smallest integer greater than or equal to each element of 
an array. 

In [95]:
arr = np.array([1.2, 2.7, 3.5, 4.9]) 
ceiled_arr = np.ceil(arr) 
print(ceiled_arr)

[2. 3. 4. 5.]


In [96]:
np.ceil(np.random.random((2,3))*100)

array([[73., 53., 53.],
       [90., 82., 24.]])

# Indexing and slicing

In [98]:
 p1 = np.arange(10) 
 p2 = np.arange(12).reshape(3,4) 
 p3 = np.arange(8).reshape(2,2,2) 
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [100]:
p3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

### Indexing on 1D array 

In [101]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
print(p1[-1])

9


In [104]:
print(p1[0])

0


### Indexing on 2D array 

In [105]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [107]:
print(p2[1,2])

6


In [108]:
print(p2[2,3])

11


In [109]:
print(p2[1,0])

4


### Indexing on 3D ( Tensors) 

In [110]:
p3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [112]:
print(p3[1,0,1])

5


- EXPLANATION :Here 3D is consists of 2 ,2D array , so Firstly we take 1 because our desired is 
5 is in second matrix which is 1 .and 1 row so 0 and second column so 1

In [113]:
print(p3[0,0,0])

0


In [114]:
print(p3[1,1,0])

6


- EXPLANATION : Here first we take because our desired is 6, is in second matrix which is 1 . 
and second row so 1 and first column so 0 

### Slicing 
Fetching Multiple items 
 
### Slicing on 1D

In [115]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [117]:
print(p1[2:5])

[2 3 4]


In [118]:
print(p1[2:5:2])

[2 4]


### Slicing on 2D

In [119]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [121]:
print(p2[0, :])

[0 1 2 3]


In [122]:
print(
p2[:,2] )

[ 2  6 10]


In [123]:
print(p2[1:3 ,1:3])

[[ 5  6]
 [ 9 10]]


In [124]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [125]:
print(p2[::2, ::3])

[[ 0  3]
 [ 8 11]]


In [126]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Slicing in 3D

In [127]:
p3 = np.arange(27).reshape(3,3,3) 
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [128]:
print(p3[1,:,1] )

[10 13 16]


In [129]:
print(p3[2, 1: ,1:] )

[[22 23]
 [25 26]]


In [130]:
print(p3[0::2] )

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [131]:
print(p3[0::2 , 0 , ::2] )

[[ 0  2]
 [18 20]]


## Iterating

In [132]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [134]:
# Looping on 1D array 
 
for i in p1: 
   print(i)

0
1
2
3
4
5
6
7
8
9


In [135]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [136]:
for i in p2: 
   print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [137]:
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [138]:
for i in p3: 
   print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [139]:
for i in np.nditer(p3): 
   print(i) 

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


## Reshaping 
 Transpose ---> Converts rows in to clumns ad columns into rows 

In [140]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [141]:
np.transpose(p2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [142]:
p2.T 

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [143]:
p3.T

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

# Ravel 
Converting any dimensions to 1D 

In [144]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [145]:
p2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [146]:
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [147]:
p3.ravel() 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# Stacking 
 
Stacking is the concept of joining arrays in NumPy. Arrays having the same dimensions can be 
stacked 

In [148]:
# Horizontal stacking 
 
w1 = np.arange(12).reshape(3,4) 
w2 = np.arange(12,24).reshape(3,4) 

In [149]:
w1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [150]:
w2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [152]:
np.hstack((w1,w2))  #using hstack for Horizontal stacking

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [153]:
w1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [154]:
w2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [155]:
np.vstack((w1,w2)) #using vstack for vertical stacking

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Splitting 
its opposite of Stacking 

In [156]:
w1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [157]:
np.hsplit(w1,2) # splitting by 2 

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [158]:
np.hsplit(w1,4) 

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [159]:
w2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [160]:
np.vsplit(w2,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]