# Numpy Crash Course

In [1]:
import numpy as np

In [2]:
np.__version__

'2.1.3'

In [3]:
import sys 
sys.version

'3.13.5 | packaged by Anaconda, Inc. | (main, Jun 12 2025, 16:37:03) [MSC v.1929 64 bit (AMD64)]'

# Creating array

In [4]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [6]:
type(my_list)

list

In [8]:
arr = np.array(my_list) 
arr

array([0, 1, 2, 3, 4, 5])

In [9]:
type(arr)

numpy.ndarray

In [10]:
type(my_list)

list

In [11]:
np. # we learn important function 

SyntaxError: invalid syntax (1655120754.py, line 1)

In [12]:
np.arange(15) 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
np.arange(3.0)  

array([0., 1., 2.])

In [14]:
np.arange(10) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(0, 5)

array([0, 1, 2, 3, 4])

In [16]:
np.arange(10,20) 

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [17]:
np.arange(20,10) # 1st arg < 2nd arg

array([], dtype=int64)

In [18]:
np.arange(-20,10) 

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [19]:
np.arange(-16,10) 

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [20]:
np.arange(-20,-10) 

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [21]:
np.arange(30,20)  # 1st arg always be < then 2nd arg

array([], dtype=int64)

In [22]:
ar = np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [23]:
np.arange(10,10) 

array([], dtype=int64)

In [24]:
np.arange()

TypeError: arange() requires stop to be specified.

In [25]:
np.arange(10,30,5)  # 10- starting from 30- end point 5 - step count

array([10, 15, 20, 25])

In [26]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [27]:
np.arange(10,30,5,8)

TypeError: Cannot interpret '8' as a data type

In [28]:
np.zeros(3) # parameter  tunning 

array([0., 0., 0.])

In [29]:
np.zeros(5, dtype=int) # hyperparameter tunning 

array([0, 0, 0, 0, 0])

In [30]:
np.zeros((2,2), dtype=int)

array([[0, 0],
       [0, 0]])

In [31]:
zero = np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [32]:
zero = np.zeros([2,2])
print(zero)

print('####')

print(type(zero))

[[0. 0.]
 [0. 0.]]
####
<class 'numpy.ndarray'>


In [33]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [34]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [35]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [36]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [37]:
np.zeros((5,10)) # bydefaul 1arge -- will give row & 2nd arg - columns

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [38]:
n = (6,7)
n1 = (6,8)
print(np.zeros(n1)) # parameter tunnin g

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [39]:
print(np.zeros(n,dtype=int)) ## hypyerparameter tunning 

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [40]:
n

(6, 7)

In [41]:
n1

(6, 8)

In [42]:
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [43]:
np.ones(3)

array([1., 1., 1.])

In [44]:
np.ones(4, dtype=int) 

array([1, 1, 1, 1])

In [45]:
np.ones(4)

array([1., 1., 1., 1.])

In [46]:
n

(6, 7)

In [47]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [48]:
np.ones((5,4),dtype=int) # by default 5- rows & 4 - columns

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [49]:
np.twos((2,3)) 

AttributeError: module 'numpy' has no attribute 'twos'

In [50]:
np.three(2,3)

AttributeError: module 'numpy' has no attribute 'three'

In [51]:
np.ones(2)

array([1., 1.])

In [52]:
np.ones((2,4)) 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [53]:
np.ones((6,10),dtype = int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [54]:
range(5)

range(0, 5)

In [55]:
r = range(5)
r

range(0, 5)

In [56]:
for i in r:
    print(i)

0
1
2
3
4


In [57]:
list(range(5))

[0, 1, 2, 3, 4]

In [58]:
range(1,10)

range(1, 10)

In [59]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [60]:
list(range(1,10,3))

[1, 4, 7]

In [61]:
y = list(range(12))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [62]:
rand(3,2)

NameError: name 'rand' is not defined

In [63]:
rand(3,2)
random.rand(3,2)

NameError: name 'rand' is not defined

In [64]:
np.random.rand(3,2)

array([[0.75221171, 0.11520416],
       [0.74177732, 0.93992429],
       [0.64839515, 0.64242044]])

In [65]:
np.random.rand(5)

array([0.71408487, 0.7174124 , 0.42746734, 0.9787469 , 0.50549279])

In [66]:
np.random.rand(2,4)

array([[0.4790167 , 0.06128412, 0.03205812, 0.97580101],
       [0.36705842, 0.64454396, 0.86234116, 0.0728866 ]])

In [67]:
np.random.randint(2,4)

3

In [68]:
np.random.randint(2,20) # 2nd argument is exlusive 

19

In [69]:
np.random.randint(0,1) 

0

In [76]:
print(np.random.randint(10,20,5))

[19 10 17 14 11]


In [78]:
print(np.random.randint(1,6,4))

[1 1 4 4]


In [79]:
print(np.random.rand(3))

[0.21596808 0.10478528 0.86309672]


In [80]:
print(np.random.randint(1))

0


In [81]:
np.random.randint(30,20,10)

ValueError: low >= high

In [82]:
print(np.random.randint(-30,20,10))

[  2   5  15  18   8   6  -8  15 -27   2]


In [83]:
print(np.random.randint(20,30,10) )

[26 24 21 29 22 21 22 27 26 23]


In [85]:
print(np.random.randint(5,9))

7


In [86]:
print(np.random.randint(10,21,3))

[15 19 19]


In [87]:
print(np.random.randint(1,12,10))

[9 8 8 8 8 1 1 5 7 1]


In [89]:
print(np.random.randint(10,40,(10,10))) #generre the element 10 -30 with 4*4 mtri

[[16 30 33 25 23 26 14 32 25 16]
 [31 17 15 25 39 20 16 18 29 33]
 [22 34 22 35 11 29 14 32 14 14]
 [18 12 17 20 24 37 19 19 32 11]
 [34 10 26 29 15 23 20 16 14 37]
 [17 24 38 38 11 20 30 38 19 32]
 [12 32 12 30 10 35 12 10 26 26]
 [11 22 36 23 12 19 36 31 16 28]
 [30 26 38 19 17 14 35 36 38 12]
 [24 22 15 31 25 34 28 36 19 27]]


In [90]:
print(np.random.randint(1,100,(12,12)))

[[34 85 78 76 32 22 20 15 50  2 75  5]
 [68 18 55 80  4 78 72 59 60 18 73  4]
 [81 52 11 31 53 93 59 81 86  1 86 73]
 [ 8 72 38 60 92  6 82 98 44 93 42 51]
 [79 64 83 19 98 52 26  8  6 72 50 40]
 [48 21  8 96 40 80 64 13 29 29 47 98]
 [97 71 17 62 85 90 12 70 99 15 91 77]
 [42 96 64 36 33  7 63  4 82 37  7 89]
 [45 49 11 63 20  6 45 86 65 25  3 86]
 [81 14 70 16 61 45 48 94 21 99 48 19]
 [48 57 55 46 14 96 30 17 54 54 37 38]
 [37 29 49 46 76 82 42 77 63 11 23 27]]


In [91]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [97]:
np.arange(1,13).reshape(12, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [99]:
b = np.random.randint(10,20,(5,4))
print(b)

[[19 11 13 15]
 [13 15 15 12]
 [11 11 19 15]
 [19 13 13 15]
 [17 10 11 10]]


In [100]:
type(b)

numpy.ndarray

In [101]:
print(b)

[[19 11 13 15]
 [13 15 15 12]
 [11 11 19 15]
 [19 13 13 15]
 [17 10 11 10]]


In [102]:
print(b[:])

[[19 11 13 15]
 [13 15 15 12]
 [11 11 19 15]
 [19 13 13 15]
 [17 10 11 10]]


In [103]:
print(b[1:3])

[[13 15 15 12]
 [11 11 19 15]]


In [104]:
print(b)

[[19 11 13 15]
 [13 15 15 12]
 [11 11 19 15]
 [19 13 13 15]
 [17 10 11 10]]


In [105]:
print(b[1,2])

15


In [106]:
print(b)

[[19 11 13 15]
 [13 15 15 12]
 [11 11 19 15]
 [19 13 13 15]
 [17 10 11 10]]


In [107]:
print(b[1,3])

12


In [108]:
print(b[1,-1])

12


In [109]:
print(b)

[[19 11 13 15]
 [13 15 15 12]
 [11 11 19 15]
 [19 13 13 15]
 [17 10 11 10]]


In [110]:
print(b[2:3])

[[11 11 19 15]]


In [111]:
print(b)

[[19 11 13 15]
 [13 15 15 12]
 [11 11 19 15]
 [19 13 13 15]
 [17 10 11 10]]


In [112]:
print(b[0:-2] )

[[19 11 13 15]
 [13 15 15 12]
 [11 11 19 15]]


In [113]:
print(b)

[[19 11 13 15]
 [13 15 15 12]
 [11 11 19 15]
 [19 13 13 15]
 [17 10 11 10]]


In [114]:
print(b[0,2])

13


In [115]:
print(b)

[[19 11 13 15]
 [13 15 15 12]
 [11 11 19 15]
 [19 13 13 15]
 [17 10 11 10]]


In [116]:
print(b[-5,-3])

11


In [117]:
print(b)

[[19 11 13 15]
 [13 15 15 12]
 [11 11 19 15]
 [19 13 13 15]
 [17 10 11 10]]


In [118]:
print(b[-4,2])

15


In [119]:
print(np.random.randint(10,20,(4,4)))

[[18 11 16 19]
 [10 12 15 16]
 [18 14 19 14]
 [16 19 17 14]]


In [120]:
print(b)

[[19 11 13 15]
 [13 15 15 12]
 [11 11 19 15]
 [19 13 13 15]
 [17 10 11 10]]


In [121]:
print(b[-4:2] )

[[13 15 15 12]]


In [122]:
print(b[:] )

[[19 11 13 15]
 [13 15 15 12]
 [11 11 19 15]
 [19 13 13 15]
 [17 10 11 10]]


## Operations

In [124]:
a = np.random.randint(10,20,10)
print(a)

[16 18 18 12 16 15 19 13 12 18]


In [125]:
id(a)

1646173178832

In [126]:
arr

array([0, 1, 2, 3, 4, 5])

In [130]:
arr2 = np.random.randint(0,100,(10,10))
print(arr2)

[[32 81 64 63 14 58 52 90 60 15]
 [72 55 20 64 83 38 95 97 50 76]
 [67 89 10 66 17 75 95 44 27 58]
 [75 66 44 69 80 13 87 22  1 10]
 [ 2 11  8 87 71 24 56 18 91 19]
 [45  6 49 25 48 29 64 14 82 53]
 [75  0 35 22  0 16 48 74 85 88]
 [ 1 15 62 76  2 75 45 97 38 70]
 [94 99 19 39 15 94  7 40 72 78]
 [22 58  9 52  7 19 38  6 93 62]]


In [131]:
print(arr)

[0 1 2 3 4 5]


In [132]:
print(arr[:])

[0 1 2 3 4 5]


In [133]:
print(arr)

[0 1 2 3 4 5]


In [134]:
print(arr[:4])

[0 1 2 3]


In [135]:
print(arr2[:])

[[32 81 64 63 14 58 52 90 60 15]
 [72 55 20 64 83 38 95 97 50 76]
 [67 89 10 66 17 75 95 44 27 58]
 [75 66 44 69 80 13 87 22  1 10]
 [ 2 11  8 87 71 24 56 18 91 19]
 [45  6 49 25 48 29 64 14 82 53]
 [75  0 35 22  0 16 48 74 85 88]
 [ 1 15 62 76  2 75 45 97 38 70]
 [94 99 19 39 15 94  7 40 72 78]
 [22 58  9 52  7 19 38  6 93 62]]


In [136]:
print(arr2[:5])

[[32 81 64 63 14 58 52 90 60 15]
 [72 55 20 64 83 38 95 97 50 76]
 [67 89 10 66 17 75 95 44 27 58]
 [75 66 44 69 80 13 87 22  1 10]
 [ 2 11  8 87 71 24 56 18 91 19]]


In [137]:
print(arr2)

[[32 81 64 63 14 58 52 90 60 15]
 [72 55 20 64 83 38 95 97 50 76]
 [67 89 10 66 17 75 95 44 27 58]
 [75 66 44 69 80 13 87 22  1 10]
 [ 2 11  8 87 71 24 56 18 91 19]
 [45  6 49 25 48 29 64 14 82 53]
 [75  0 35 22  0 16 48 74 85 88]
 [ 1 15 62 76  2 75 45 97 38 70]
 [94 99 19 39 15 94  7 40 72 78]
 [22 58  9 52  7 19 38  6 93 62]]


In [139]:
print(arr2[1,4])

83


In [140]:
print(arr2)

[[32 81 64 63 14 58 52 90 60 15]
 [72 55 20 64 83 38 95 97 50 76]
 [67 89 10 66 17 75 95 44 27 58]
 [75 66 44 69 80 13 87 22  1 10]
 [ 2 11  8 87 71 24 56 18 91 19]
 [45  6 49 25 48 29 64 14 82 53]
 [75  0 35 22  0 16 48 74 85 88]
 [ 1 15 62 76  2 75 45 97 38 70]
 [94 99 19 39 15 94  7 40 72 78]
 [22 58  9 52  7 19 38  6 93 62]]


In [142]:
print(arr2[-5,5])

29


In [143]:
print(arr2[-5,-5])

29


In [144]:
print(arr2[::-1])

[[22 58  9 52  7 19 38  6 93 62]
 [94 99 19 39 15 94  7 40 72 78]
 [ 1 15 62 76  2 75 45 97 38 70]
 [75  0 35 22  0 16 48 74 85 88]
 [45  6 49 25 48 29 64 14 82 53]
 [ 2 11  8 87 71 24 56 18 91 19]
 [75 66 44 69 80 13 87 22  1 10]
 [67 89 10 66 17 75 95 44 27 58]
 [72 55 20 64 83 38 95 97 50 76]
 [32 81 64 63 14 58 52 90 60 15]]


In [145]:
print(arr2[::-2])

[[22 58  9 52  7 19 38  6 93 62]
 [ 1 15 62 76  2 75 45 97 38 70]
 [45  6 49 25 48 29 64 14 82 53]
 [75 66 44 69 80 13 87 22  1 10]
 [72 55 20 64 83 38 95 97 50 76]]


In [146]:
print(arr2[::-3])

[[22 58  9 52  7 19 38  6 93 62]
 [75  0 35 22  0 16 48 74 85 88]
 [75 66 44 69 80 13 87 22  1 10]
 [32 81 64 63 14 58 52 90 60 15]]


In [148]:
print(arr.max())

5


In [149]:
print(arr.min())

0


In [150]:
print(arr)

[0 1 2 3 4 5]


In [151]:
print(arr2.mean())

48.43


In [152]:
print(arr2.max())

99


In [153]:
print(arr2.min())

0


In [155]:
from numpy import *
a = array([1,2,3,4,9])
print(median(a))

3.0


# Without work on import* can you please find the median, mode)

In [156]:
print(arr)

[0 1 2 3 4 5]


In [157]:
print(arr.reshape(3,2))

[[0 1]
 [2 3]
 [4 5]]


In [159]:
print(arr.reshape(6,1))

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [160]:
print(arr.reshape(1,6))

[[0 1 2 3 4 5]]


In [161]:
print(arr)

[0 1 2 3 4 5]


In [162]:
print(arr.reshape(2,4))

ValueError: cannot reshape array of size 6 into shape (2,4)

In [163]:
print(arr.reshape(2,3,order='C'))

[[0 1 2]
 [3 4 5]]


In [164]:
print(arr.reshape(2,3,order='F')) # print element with fortran 

[[0 2 4]
 [1 3 5]]


In [165]:
print(arr.reshape(2,3,order='A')) # A almost give you c type output

[[0 1 2]
 [3 4 5]]


In [166]:
print(arr)

[0 1 2 3 4 5]


In [167]:
print(arr.reshape(2,3)) 

[[0 1 2]
 [3 4 5]]


In [168]:
print(arr.reshape(1,4))

ValueError: cannot reshape array of size 6 into shape (1,4)

In [169]:
print(arr.reshape(1,6))

[[0 1 2 3 4 5]]


In [170]:
print(arr.reshape(6,1))

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [171]:
print(arr.reshape(1,6))

[[0 1 2 3 4 5]]


In [172]:
print(arr.reshape(6,1))

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [173]:
print(arr.reshape(3,3))

ValueError: cannot reshape array of size 6 into shape (3,3)

In [174]:
print(arr.reshape(2,3))

[[0 1 2]
 [3 4 5]]


In [175]:
print(arr)

[0 1 2 3 4 5]


## Indexing

In [178]:
mat = np.arange(0,100).reshape(10,10) 
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [179]:
row = 4
col = 5

In [180]:
row

4

In [181]:
col

5

In [182]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [184]:
print(mat[row,col])

45


In [186]:
print(mat[4,5])

45


In [187]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [188]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [190]:
col = 6

In [191]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [192]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [193]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [194]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [195]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [196]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [197]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [198]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [199]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [200]:
row

4

In [201]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [202]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [203]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [204]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [205]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [206]:
mat[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [208]:
print(mat[1,4])

14


In [209]:
print(mat[3:-3])

[[30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]]


In [210]:
print(mat[0])

[0 1 2 3 4 5 6 7 8 9]


In [212]:
print(mat[6])

[60 61 62 63 64 65 66 67 68 69]


In [214]:
print((mat[0:10]))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [215]:
print(mat[0:10:3])

[[ 0  1  2  3  4  5  6  7  8  9]
 [30 31 32 33 34 35 36 37 38 39]
 [60 61 62 63 64 65 66 67 68 69]
 [90 91 92 93 94 95 96 97 98 99]]


In [216]:
print(mat[0:10])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [217]:
print(mat[4:])

[[40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [218]:
print(mat[:4])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]]


In [219]:
print(mat[::-1])

[[90 91 92 93 94 95 96 97 98 99]
 [80 81 82 83 84 85 86 87 88 89]
 [70 71 72 73 74 75 76 77 78 79]
 [60 61 62 63 64 65 66 67 68 69]
 [50 51 52 53 54 55 56 57 58 59]
 [40 41 42 43 44 45 46 47 48 49]
 [30 31 32 33 34 35 36 37 38 39]
 [20 21 22 23 24 25 26 27 28 29]
 [10 11 12 13 14 15 16 17 18 19]
 [ 0  1  2  3  4  5  6  7  8  9]]


In [220]:
print(mat[::-3])

[[90 91 92 93 94 95 96 97 98 99]
 [60 61 62 63 64 65 66 67 68 69]
 [30 31 32 33 34 35 36 37 38 39]
 [ 0  1  2  3  4  5  6  7  8  9]]


In [221]:
print(mat[::-5])

[[90 91 92 93 94 95 96 97 98 99]
 [40 41 42 43 44 45 46 47 48 49]]


In [222]:
print(mat[2:6])

[[20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]]


In [223]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [224]:
print(mat[2:6,2:4])

[[22 23]
 [32 33]
 [42 43]
 [52 53]]


In [225]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [226]:
print(mat[1:2,2:4] )

[[12 13]]


In [227]:
print(mat[2:3,2:3])

[[22]]


In [228]:
print(mat[2:4,3:5])

[[23 24]
 [33 34]]


In [229]:
print(mat[3:5,2:4])

[[32 33]
 [42 43]]


In [230]:
print(mat[2:3,4:5])

[[24]]


## Masking

In [231]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [232]:
id(mat)

1646174992208

In [233]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [234]:
print(mat[mat<50])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [235]:
print(mat[mat<=50])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50]


In [236]:
print(mat>50)

[[False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]]


In [237]:
print(mat[mat==50] )

[50]


In [238]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [244]:
a1 = mat[mat<50] 
print(a1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [245]:
a2 = mat[mat>50] 
print(a2)

[51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74
 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98
 99]


In [248]:
a3 = mat[mat<=50] 
print(a3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50]


In [249]:
a4 = mat[mat==50]
print(a4)

[50]


# Python program to generat otp 

In [251]:
import random

def generate_otp(length=4):
    """Generate a numeric OTP of a specified length."""
    digits = '012345'
    otp = ''.join(random.choice(digits) for _ in range(length))
    return otp

# Example usage
otp_length = 4  # You can change this to any length you prefer
otp = generate_otp(otp_length)
print(f"Your OTP is: {otp}")

Your OTP is: 1241


In [252]:
def wish():
    print('good even')
wish()

def wish():
    print('good even')
wish()

def wish():
    print('good even')
wish()

good even
good even
good even


In [253]:
def wish():
    print('good even')
wish()

wish()

wish()

good even
good even
good even


In [255]:
list1=['a','b','g',1,5]
print(list1.pop)

<built-in method pop of list object at 0x0000017F47825DC0>


In [256]:
x = [1, 2, 3]
y = x.copy()
x.append(4)
print(x)

[1, 2, 3, 4]
